version: "3.8"

services:
  financial-analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: financial-analyzer
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./reports:/app/reports
      - ./logs:/app/logs
      - ./config:/app/config
      - ./templates:/app/templates
      - ./data:/app/data
    command: >
      python3 src/main.py AAPL --format both
    depends_on:
      - redis
    networks:
      - financial-network
    restart: unless-stopped
    # Optional: expose port for web API or dashboard in the future
    ports:
      - "8000:8000"

  redis:
    image: redis:7-alpine
    container_name: financial-redis
    restart: unless-stopped
    networks:
      - financial-network
    volumes:
      - redis-data:/data

volumes:
  redis-data:

networks:
  financial-network:
    driver: bridge
